language: java
jdk: 
    - oraclejdk8
services: 
    - mysql
test:
  adapter: mysql2
  database: kts_test
  username: root
  encoding: utf8
before_install:
  - pwd 
  - pwd
  - pwd
  - pwd
  - mkdir randomdir
  - ls
  - mysql -u root -e "CREATE DATABASE kts_test"
  - mysql -u root -e "CREATE DATABASE kts_prod"
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');"
  - mysql --user="root" --password="root" kts_test < ./src/test/resources/populate.sql

