(function(){
	angular
		.module('kits',[
			'ngRoute',
			'ngCookies',
			'ngMaterial',
			'ngMessages',
			'lfNgMdFileInput',
			'toastr',
			'kits.login',
			'kits.register',
			'kits.report',
			'kits.create_building',
			'kits.create_meeting',
			'kits.create_proposal',
			'kits.manager_buildings',
			'kits.manager_meetings',
			'kits.manager_proposals',
			'kits.building_reports',
			'kits.building_proposals',
			'kits.buildings',
			'kits.building',
			'kits.display_report',
			'kits.buildings',
			'kits.users',
			'kits.create_residence',
			'kits.residence'
		])
})();